# make local-image-icq-demo
# docker run --rm -it icq-demo:local q interquery

FROM golang:1.26-alpine AS builder

RUN set -eux; apk add --no-cache git libusb-dev linux-headers gcc musl-dev make;

ENV GOPATH=""

COPY go.mod .
COPY go.sum .
COPY Makefile .

RUN go mod download

COPY ./testing/demo-simapp .

RUN make build

FROM alpine:3.21

COPY --from=builder /go/build/* /bin/icq-demo

ENTRYPOINT ["/bin/icq-demo"]