name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  pr-labler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          dot: true