name: rate-limiting
on:
  pull_request:
    paths:
      - "modules/rate-limiting/**"
      - ".github/workflows/rate-limiting.yml"

env:
  LINT_VERSION: v1.57.1
  GO_VERSION: 1.22.1
  WORKING_DIRECTORY: modules/rate-limiting

  DOCKER_TAG: rate-limiting:local
  TAR_PATH: /tmp/rate-limiting-image.tar
  IMAGE_NAME: rate-limiting-image

jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
      - name: run linting
        if: env.GIT_DIFF
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          make lint

  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v4

      - name: Test
        run: go test ./...
        working-directory: ${{ env.WORKING_DIRECTORY }}

# TODO: build docker & run e2e tests (ref: pfm matrix)